# coding: utf-8

# flake8: noqa

"""
Model Registry REST API

REST API for Model Registry to create and manage ML model metadata

The version of the OpenAPI document: v1alpha3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from kubeflow.mr_openapi.api.model_registry_service_api import ModelRegistryServiceApi

# import ApiClient
from kubeflow.mr_openapi.api_response import ApiResponse
from kubeflow.mr_openapi.api_client import ApiClient
from kubeflow.mr_openapi.configuration import Configuration
from kubeflow.mr_openapi.exceptions import OpenApiException
from kubeflow.mr_openapi.exceptions import ApiTypeError
from kubeflow.mr_openapi.exceptions import ApiValueError
from kubeflow.mr_openapi.exceptions import ApiKeyError
from kubeflow.mr_openapi.exceptions import ApiAttributeError
from kubeflow.mr_openapi.exceptions import ApiException

# import models into sdk package
from kubeflow.mr_openapi.models.artifact import Artifact
from kubeflow.mr_openapi.models.artifact_create import ArtifactCreate
from kubeflow.mr_openapi.models.artifact_list import ArtifactList
from kubeflow.mr_openapi.models.artifact_state import ArtifactState
from kubeflow.mr_openapi.models.artifact_update import ArtifactUpdate
from kubeflow.mr_openapi.models.base_model import BaseModel
from kubeflow.mr_openapi.models.base_resource import BaseResource
from kubeflow.mr_openapi.models.base_resource_create import BaseResourceCreate
from kubeflow.mr_openapi.models.base_resource_dates import BaseResourceDates
from kubeflow.mr_openapi.models.base_resource_list import BaseResourceList
from kubeflow.mr_openapi.models.base_resource_update import BaseResourceUpdate
from kubeflow.mr_openapi.models.doc_artifact import DocArtifact
from kubeflow.mr_openapi.models.doc_artifact_create import DocArtifactCreate
from kubeflow.mr_openapi.models.doc_artifact_update import DocArtifactUpdate
from kubeflow.mr_openapi.models.error import Error
from kubeflow.mr_openapi.models.execution_state import ExecutionState
from kubeflow.mr_openapi.models.inference_service import InferenceService
from kubeflow.mr_openapi.models.inference_service_create import InferenceServiceCreate
from kubeflow.mr_openapi.models.inference_service_list import InferenceServiceList
from kubeflow.mr_openapi.models.inference_service_state import InferenceServiceState
from kubeflow.mr_openapi.models.inference_service_update import InferenceServiceUpdate
from kubeflow.mr_openapi.models.metadata_bool_value import MetadataBoolValue
from kubeflow.mr_openapi.models.metadata_double_value import MetadataDoubleValue
from kubeflow.mr_openapi.models.metadata_int_value import MetadataIntValue
from kubeflow.mr_openapi.models.metadata_proto_value import MetadataProtoValue
from kubeflow.mr_openapi.models.metadata_string_value import MetadataStringValue
from kubeflow.mr_openapi.models.metadata_struct_value import MetadataStructValue
from kubeflow.mr_openapi.models.metadata_value import MetadataValue
from kubeflow.mr_openapi.models.model_artifact import ModelArtifact
from kubeflow.mr_openapi.models.model_artifact_create import ModelArtifactCreate
from kubeflow.mr_openapi.models.model_artifact_list import ModelArtifactList
from kubeflow.mr_openapi.models.model_artifact_update import ModelArtifactUpdate
from kubeflow.mr_openapi.models.model_version import ModelVersion
from kubeflow.mr_openapi.models.model_version_create import ModelVersionCreate
from kubeflow.mr_openapi.models.model_version_list import ModelVersionList
from kubeflow.mr_openapi.models.model_version_state import ModelVersionState
from kubeflow.mr_openapi.models.model_version_update import ModelVersionUpdate
from kubeflow.mr_openapi.models.order_by_field import OrderByField
from kubeflow.mr_openapi.models.registered_model import RegisteredModel
from kubeflow.mr_openapi.models.registered_model_create import RegisteredModelCreate
from kubeflow.mr_openapi.models.registered_model_list import RegisteredModelList
from kubeflow.mr_openapi.models.registered_model_state import RegisteredModelState
from kubeflow.mr_openapi.models.registered_model_update import RegisteredModelUpdate
from kubeflow.mr_openapi.models.serve_model import ServeModel
from kubeflow.mr_openapi.models.serve_model_create import ServeModelCreate
from kubeflow.mr_openapi.models.serve_model_list import ServeModelList
from kubeflow.mr_openapi.models.serve_model_update import ServeModelUpdate
from kubeflow.mr_openapi.models.serving_environment import ServingEnvironment
from kubeflow.mr_openapi.models.serving_environment_create import ServingEnvironmentCreate
from kubeflow.mr_openapi.models.serving_environment_list import ServingEnvironmentList
from kubeflow.mr_openapi.models.serving_environment_update import ServingEnvironmentUpdate
from kubeflow.mr_openapi.models.sort_order import SortOrder
